# Generated by Django 5.2.1 on 2025-06-07 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoriainventario',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditoriainventario',
            name='bloqueado',
            field=models.BooleanField(default=False),
        ),
    ]
