# Generated by Django 5.2.1 on 2025-06-12 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_remove_proveedor_contacto_proveedor_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='contacto',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
