# Generated by Django 5.2.1 on 2025-06-13 01:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_proveedor_contacto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(max_length=50, unique=True)),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('cantidad_inicial', models.PositiveIntegerField()),
                ('cantidad_actual', models.PositiveIntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='inventario.producto')),
            ],
            options={
                'ordering': ['fecha_vencimiento'],
                'unique_together': {('producto', 'numero_lote')},
            },
        ),
        migrations.CreateModel(
            name='HistorialLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cambio', models.CharField(choices=[('creacion', 'Creación de lote'), ('uso', 'Uso de lote'), ('devolucion', 'Devolución al lote'), ('vencimiento', 'Marcado como vencido'), ('eliminacion', 'Eliminación de lote')], max_length=20)),
                ('cantidad_anterior', models.PositiveIntegerField()),
                ('cantidad_nueva', models.PositiveIntegerField()),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='inventario.loteproducto')),
            ],
            options={
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.loteproducto'),
        ),
    ]
