# Generated by Django 5.2.1 on 2025-06-20 20:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_loteproducto_historiallote_movimientoinventario_lote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kitproducto',
            options={'ordering': ['nombre'], 'verbose_name': 'Kit de Producto', 'verbose_name_plural': 'Kits de Productos'},
        ),
        migrations.AlterModelOptions(
            name='productoenkit',
            options={'verbose_name': 'Producto en Kit', 'verbose_name_plural': 'Productos en Kits'},
        ),
        migrations.RemoveField(
            model_name='kitproducto',
            name='productos',
        ),
        migrations.AddField(
            model_name='kitproducto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='kitproducto',
            name='categoria',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='kitproducto',
            name='codigo',
            field=models.CharField(default='ll4', max_length=50),
        ),
        migrations.AddField(
            model_name='kitproducto',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='kitproducto',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='kitproducto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productoenkit',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='productoenkit',
            unique_together={('kit', 'producto')},
        ),
    ]
