# Generated by Django 5.2.1 on 2025-06-20 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_configuracionsistema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaInformeInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('filtros_aplicados', models.TextField(help_text='Filtros usados al generar el informe (formato JSON o texto plano).')),
                ('tipo_exportacion', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel')], help_text='Formato en que se exportó el informe.', max_length=10)),
                ('total_registros', models.PositiveIntegerField(help_text='Cantidad de productos exportados.')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
