# Generated by Django 5.2.1 on 2025-06-27 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_ordencompra_fecha_aprobacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemordencompra',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
