# Generated by Django 5.2.1 on 2025-06-27 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_itemordencompra_precio_unitario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loteproducto',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
