# Generated by Django 5.2.1 on 2025-06-30 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_alter_kitproducto_options_and_more'),
        ('inventario', '0014_alter_loteproducto_fecha_vencimiento'),
    ]

    operations = [
    ]
